name: ProtocolStringReplacer
version: @versionName@
main: io.github.rothes.protocolstringreplacer.ProtocolStringReplacer
author: Rothes
api-version: 1.13
folia-supported: true
softdepend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  protocolstringreplacer:
    aliases: [psr]
    description: ProtocolStringReplacer commands.
permissions:
  protocolstringreplacer.command.edit:
    description: allow you to edit the replacer configs.
    default: op
  protocolstringreplacer.command.parse:
    description: allow you to parse a String.
    default: op
  protocolstringreplacer.command.reload:
    description: allow you to reload the configs.
    default: op
  protocolstringreplacer.feature.usermetacache:
    description: save the itemmeta when editing, and restore the original one when the player in creative interacts it.
    default: op
  protocolstringreplacer.feature.usermetacache.noncreative:
    description: with protocolstringreplacer.feature.usermetacache, allow to restore the original one when the player in other gamemodes interacts it.
    default: false
  protocolstringreplacer.feature.parsepapi:
    description: Parse placeholders from PlaceholderAPI for player. Set to false will prevent any papi parse.
    default: true
  protocolstringreplacer.updater.notify:
    description: allow you to receive updater info.
    default: op
