name: ProtocolStringReplacer
version: ${projectVersionString}
main: me.rothes.protocolstringreplacer.ProtocolStringReplacer
author: Rothes
api-version: 1.13
softdepend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  protocolstringreplacer:
    aliases: [psr]
    description: ProtocolStringReplacer commands.
permissions:
  protocolstringreplacer.command.edit:
    description: allow you to edit the replacer configs.
    default: op
  protocolstringreplacer.command.parse:
    description: allow you to parse a String.
    default: op
  protocolstringreplacer.command.reload:
    description: allow you to reload the configs.
    default: op
  protocolstringreplacer.feature.usermetacache:
    description: save the itemmeta when editing, and restore the original one when the player in creative interacts it.
    default: op
  protocolstringreplacer.feature.usermetacache.noncreative:
    description: with protocolstringreplacer.feature.usermetacache, allow to restore the original one when the player in other gamemodes interacts it.
    default: false
