name: ProtocolStringReplacer Snapshot Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6

      - name: Execute Gradle build
        run: ./gradlew reobfJar
      
      - run: mkdir ProtocolStringReplacer && cp build/libs/*.jar ProtocolStringReplacer
      
      - uses: actions/upload-artifact@v3
        with:
          name: ProtocolStringReplacer-Snapshot
          path: ProtocolStringReplacer
